# Configuration file for the Sphinx documentation builder.
#
# This file only contains a selection of the most common options. For a full
# list see the documentation:
# https://www.sphinx-doc.org/en/master/usage/configuration.html

# -- Path setup --------------------------------------------------------------

# If extensions (or modules to document with autodoc) are in another directory,
# add these directories to sys.path here. If the directory is relative to the
# documentation root, use os.path.abspath to make it absolute, like shown here.
#
from recommonmark.parser import CommonMarkParser
import sphinx_rtd_theme
import os
import sys
from os import path

root_dir = path.dirname(path.dirname(path.dirname(__file__)))
root_dir = os.path.join(root_dir, 'pytorch_template')
sys.path.insert(0, root_dir)

# for autodoc
# == autodoc_mock_imports
# autodoc_dependency = os.path.join(root_dir, "requirements.txt")
# os.system("pip install -r {}".format(autodoc_dependency))

# -- Project information -----------------------------------------------------

project = 'pytorch template'
copyright = '2021, jiannan chen'
author = 'jiannan chen'

# The full version, including alpha/beta/rc tags
release = '0.0.1'

# -- General configuration ---------------------------------------------------

# Add any Sphinx extension module names here, as strings. They can be
# extensions coming with Sphinx (named 'sphinx.ext.*') or your custom
# ones.
extensions = [
    'sphinx.ext.autodoc',
    'sphinx.ext.coverage',
    'sphinx.ext.viewcode',
    "sphinx_rtd_theme",
    'sphinx_togglebutton',
    'sphinx.ext.napoleon',
]

# Add any paths that contain templates here, relative to this directory.
templates_path = ['_templates']

# The language for content autogenerated by Sphinx. Refer to documentation
# for a list of supported languages.
#
# This is also used if you do content translation via gettext catalogs.
# Usually you set "language" from the command line for these cases.
language = 'zh_CN'

html_use_index = True
# List of patterns, relative to source directory, that match files and
# directories to ignore when looking for source files.
# This pattern also affects html_static_path and html_extra_path.
exclude_patterns = []

# -- Options for HTML output -------------------------------------------------

# The theme to use for HTML and HTML Help pages.  See the documentation for
# a list of builtin themes.
#
source_suffix = ['.rst', '.md', '.MD']
html_theme = 'sphinx_rtd_theme'
add_module_names = False
source_parsers = {
    '.md': CommonMarkParser,
    '.MD': CommonMarkParser,
}
# Add any paths that contain custom static files (such as style sheets) here,
# relative to this directory. They are copied after the builtin static files,
# so a file named "default.css" will overwrite the builtin "default.css".
latex_engine = 'xelatex'
latex_elements = {
    'papersize':
    'a4paper',
    'pointsize':
    '11pt',
    'extraclassoptions':
    'oneside',
    'preamble':
    r'''
\usepackage[titles]{tocloft}
\usepackage{ctex}
\setmainfont{Noto Serif}
\setsansfont{Noto Sans}
\setmonofont{Noto Sans Mono}
\setCJKmainfont{Noto Serif CJK SC}
\setCJKsansfont{Noto Sans CJK SC}
\setCJKmonofont{Noto Sans Mono CJK SC}
'''
}